export type SortingAnimationFrame = {
  array: number[];
  activeIndices: number[] | null;
  blueIndices?: number[];
  sortedIndices: number[];
  bucketValues?: number[];
  bucketRangeStart?: number;
  bucketRangeEnd?: number;
  bucketActiveIndices?: number[];
  bucketBlueIndices?: number[];
  bucketSortedIndices?: number[];
  outputValues?: number[];
  outputActiveIndices?: number[];
  outputBlueIndices?: number[];
  outputSortedIndices?: number[];
  tournamentTreeValues?: Array<number | null>;
  tournamentTreeSourceIndices?: Array<number | null>;
  tournamentTreeActiveIndices?: number[];
  tournamentTreeBlueIndices?: number[];
  tournamentOutputValues?: Array<number | null>;
  tournamentOutputActiveIndices?: number[];
  tournamentOutputBlueIndices?: number[];
  tournamentOutputSortedIndices?: number[];
  stats: { comparisons: number; swaps: number };
  completed: boolean;
  description: string;
};
